- .github/workflows/CD.yml
- Dockerfile
- build.gradle
[FEAT] 배포 방식 docker-compose 방식으로 변경
* actuator 의존성 설치(컨테이너 health check할 때 필요)
* 도커 이미지 빌드할 때 curl 설치하는 명령어 추가(컨테이너 health check할 때 필요)
* CD.yml DEPLOY-CONFIGS 레포의 docker-compose.yml 파일 사용하여 배포하게 수정(fastapi 앱 배포와 같이 관리 + 추후에 추가될 수 있는 redis, kafka 컨테이너와 같이 관리하기 위함)
#16 
* develop 브랜치에 머지 성공하면 바로 main 브랜치에 머지 하겠습니다
* 로컬에서 health check 정상 작동 확인
> [FEAT] 배포 방식 docker-compose 방식으로 변경

- src/main/java/channeling/be/domain/channel/application/ChannelService.java
- src/main/java/channeling/be/domain/channel/application/ChannelServiceImpl.java
- src/main/java/channeling/be/domain/channel/domain/Channel.java
- src/main/java/channeling/be/domain/channel/presentation/ChannelController.java
- src/main/java/channeling/be/domain/channel/presentation/converter/ChannelConverter.java
- src/main/java/channeling/be/domain/channel/presentation/dto/request/ChannelRequestDto.java
- src/main/java/channeling/be/domain/channel/presentation/dto/response/ChannelResponseDto.java
- src/main/java/channeling/be/response/code/status/ErrorStatus.java
- src/main/java/channeling/be/response/exception/handler/ChannelHandler.java
[FEAT]: 채널 컨셉 수정 
채널 컨셉 수정을 합니다.
-- 테스트 db 삽입 --
테스트 멤버
테스트 채널 
--swagger 정상 응답--
-- 실행 쿼리 --
-채널 존재 확인-
select
c1_0.id,
c1_0.channel_hash_tag,
c1_0.channel_update_at,
c1_0.comment,
c1_0.concept,
c1_0.created_at,
c1_0.image,
c1_0.join_date,
c1_0.like_count,
c1_0.link,
c1_0.member_id,
c1_0.name,
c1_0.share,
c1_0.subscribe,
c1_0.target,
c1_0.updated_at,
c1_0.video_count,
c1_0.view 
from
channel c1_0 
where
c1_0.id=?
-존재하는 경우 수정 쿼리-
update channel 
set
channel_hash_tag=?,
channel_update_at=?,
comment=?,
concept=?,
created_at=?,
image=?,
join_date=?,
like_count=?,
link=?,
member_id=?,
name=?,
share=?,
subscribe=?, …
> [FEAT]: 채널 컨셉 수정 

- src/main/java/channeling/be/domain/channel/application/ChannelService.java
- src/main/java/channeling/be/domain/channel/application/ChannelServiceImpl.java
- src/main/java/channeling/be/domain/channel/domain/Channel.java
- src/main/java/channeling/be/domain/channel/presentation/ChannelController.java
- src/main/java/channeling/be/domain/channel/presentation/ChannelConverter.java
- src/main/java/channeling/be/domain/channel/presentation/converter/ChannelConverter.java
- src/main/java/channeling/be/domain/channel/presentation/dto/request/ChannelRequestDto.java
- src/main/java/channeling/be/domain/channel/presentation/dto/response/ChannelResponseDto.java
[FEAT]: 채널 타겟 층 수정 + 컨셉 수정 리펙토링
채널 타겟 층 수정 기능 구현 완료
채널 컨셉 수정 기능 url, 및 응답 결과 리팩토링
기존 DB
api 호출
db 수정 확인
존재하지 않는 아이디를 요청했을 경우
#20 
미노님께서 작성해셨던 channel 관련 url이 더 RESTful 하다고 생각하여서,
기존에 작성했던 체널 컨셉 수정과 함께 리팩토링 같이 진행하였습니다
관련해서, 응답 결과 바뀐 채널의 아이디가 응답 되어야지 프론트 쪽에서 이어서 다음 요청을 보내기 편할 것 같아 추가하였고,
성공 응답 메시지는 불필요하다고 생각되어 제거 하였습니다!
관련 코드는 컨셉 수정와 동일합니다!
> [FEAT]: 채널 타겟 층 수정 구현 완료 + 채널 컨셉 수정 리펙토링

- src/main/java/channeling/be/domain/channel/presentation/ChannelController.java
- src/main/java/channeling/be/domain/member/application/MemberService.java
- src/main/java/channeling/be/domain/member/application/MemberServiceImpl.java
- src/main/java/channeling/be/domain/member/domain/Member.java
- src/main/java/channeling/be/domain/member/domain/repository/MemberRepository.java
- src/main/java/channeling/be/domain/member/presentation/MemberController.java
- src/main/java/channeling/be/domain/member/presentation/MemberConverter.java
- src/main/java/channeling/be/domain/member/presentation/MemberReqDTO.java
- src/main/java/channeling/be/domain/member/presentation/MemberResDTO.java
- src/main/java/channeling/be/response/code/status/ErrorStatus.java
- src/main/java/channeling/be/response/code/status/SuccessStatus.java
- src/main/java/channeling/be/response/exception/handler/MemberHandler.java
[FEAT] 회원 SNS 링크 업데이트 
- SNS 링크 업데이트 로직 추가
- SNS 링크 검증 로직 추가
- 에러 코드 작성
- #22 에서 반환하는 API 의 응답 통일화
-APIResponse 적용
#30 
> [FEAT] 회원 SNS 링크 업데이트 

- src/main/java/channeling/be/domain/channel/presentation/ChannelController.java
- src/main/java/channeling/be/domain/video/application/VideoService.java
- src/main/java/channeling/be/domain/video/application/VideoServiceImpl.java
- src/main/java/channeling/be/domain/video/domain/repository/VideoRepository.java
- src/main/java/channeling/be/domain/video/presentaion/VideoResDTO.java
[REFACTOR] 동영상 조회 로직 커서기반 슬라이싱으로 변경
기존로직이 실시간으로 추가되는 DB를 고려했을때 페이징시에 중복/표시되지 않을 수 있는 비즈니스 로직 식별.
uploadDate를 통해 커서 기반 페이징으로 이를 해결
#22 
> [REFACTOR] 동영상 조회 로직 커서기반 슬라이싱으로 변경

- src/main/java/channeling/be/domain/channel/application/ChannelService.java
- src/main/java/channeling/be/domain/channel/application/ChannelServiceImpl.java
- src/main/java/channeling/be/domain/channel/presentation/ChannelController.java
- src/main/java/channeling/be/domain/channel/presentation/ChannelConverter.java
- src/main/java/channeling/be/domain/channel/presentation/ChannelResDTO.java
채널 정보 조회
채널 정보 조회 (로그인 사용자 권한 필요)
> [FEAT] 채널 정보 조회

- src/main/java/channeling/be/domain/report/domain/Report.java
[CHORE] report 테이블 video_id 제외한 칼럼들 nullable
report 테이블 video_id 제외한 칼럼들 nullable하게 변경
#36
> [CHORE] report 테이블 video_id 제외한 칼럼들 nullable

- src/main/java/channeling/be/domain/member/application/MemberService.java
- src/main/java/channeling/be/domain/member/application/MemberServiceImpl.java
- src/main/java/channeling/be/domain/member/domain/Member.java
- src/main/java/channeling/be/domain/member/domain/repository/MemberRepository.java
- src/main/java/channeling/be/domain/member/presentation/MemberController.java
- src/main/java/channeling/be/domain/member/presentation/MemberConverter.java
- src/main/java/channeling/be/domain/member/presentation/MemberReqDTO.java
- src/main/java/channeling/be/domain/member/presentation/MemberResDTO.java
- src/main/java/channeling/be/global/config/S3Config.java
- src/main/java/channeling/be/global/infrastructure/aws/S3Service.java
- src/main/java/channeling/be/response/code/status/ErrorStatus.java
- src/main/java/channeling/be/response/exception/handler/S3Handler.java
- src/main/resources/application-s3.yml
[[FEAT]: 멤버 이미지 수정 (S3 도입)]
s3 yml 파일 수정 (access, pirvate 키 추가 -> env 파일 내용 참고)
v2 버전으로 config 추가 및 util 서비스 메서드 추가
멤버 프로필 사진 수정 기능 
#34 
기존에 v1만 써봤는데, 이번 기회에 v2를 사용하게 되어서 레퍼런스에 관련 내용 추가해보았습니다.
현재는 기존 사진을 삭제하는 것은 추가하지 않았는데, 나중에 필요하면 추가하겠습니다.
> [FEAT]: 멤버 이미지 수정 (S3 도입)

- .github/workflows/CD.yml
[BUILD] 구글 로그인, jwt 관련 환경 변수 추가
- GOOGLE_CLIENT_ID 환경 변수 추가
- GOOGLE_CLIENT_SECRET 환경 변수 추가
- GOOGLE_REDIRECT_URI 환경 변수 추가
- JWT_SECRET 환경 변수 추가
- DB 이름 환경 변수로 변경
#51 
**develop 머지 성공 후 바로 main에 머지해서 테스트 에정!**
> [BUILD] 구글 로그인, jwt 관련 환경 변수 추가

- .github/workflows/CD.yml
- src/main/resources/application-db.yml
* [BUILD] 이전 Docker 이미지 삭제 step 추가
* [BUILD] redis host 환경 변수로 설정
* [BUILD] CD.yml에 redis 환경 변수 추가
---------
[Build] Redis 호스트 주소 환경 변수로 변경 + 배포 시 이전 Docker 이미지 삭제 step 추가 (#56)
- redis 호스트 주소 환경 변수로 변경했습니다.
- 배포 시 이전 Docker 이미지 삭제 step 추가
#55
> [Build] Redis 호스트 주소 환경 변수로 변경 + 배포 시 이전 Docker 이미지 삭제 step 추가 (#56)

- src/main/java/channeling/be/domain/auth/handler/Oauth2LoginFailureHandler.java
- src/main/java/channeling/be/domain/auth/handler/Oauth2LoginSuccessHandler.java
로그인 이후 현재 제이슨을 그대로 찍어내도록 응답하고 있습니다.
프로젝트에서 구현된 security oauth (서버 로그인 주도 방식) 에서는 프론트로 직접 리다이렉션을 해야 합니다.
관련 내용은 노션 [ 백엔드/트러블슈팅/로그인 후 응답 문제 ] 로 정리했습니다
https://www.notion.so/23e086918f4380938158d5f401066fae?source=copy_link
> [FIX]: 로그인 후 프론트로 리다이렉션

- src/main/java/channeling/be/domain/TrendKeyword/domain/TrendKeyword.java
[FIX] TrendKeyword 외래키 report로 변경
- 트렌드 키워드 외래키 videoId -> reportId
> [FIX] TrendKeyword 외래키 report로 변경

- src/main/java/channeling/be/domain/channel/presentation/ChannelController.java
> [REFACTOR] : 커서기반-> 페이지네이션 변경

- src/main/java/channeling/be/domain/idea/application/IdeaService.java
- src/main/java/channeling/be/domain/idea/application/IdeaServiceImpl.java
- src/main/java/channeling/be/domain/idea/domain/repository/IdeaRepository.java
- src/main/java/channeling/be/domain/idea/presentation/IdeaController.java
- src/main/java/channeling/be/domain/idea/presentation/IdeaConverter.java
- src/main/java/channeling/be/domain/idea/presentation/IdeaResDto.java
- src/main/java/channeling/be/domain/idea/presentation/IdeaSwagger.java
- src/main/java/channeling/be/domain/member/application/MemberService.java
- src/main/java/channeling/be/domain/member/presentation/MemberController.java
- src/main/java/channeling/be/domain/member/presentation/MemberSwagger.java
[FEAT]: 북마크한 아이디어 조회
1,3 번만 조회되기를 기대
--실제 출력 sql --
select
i1_0.id,
i1_0.content,
i1_0.created_at,
i1_0.hash_tag,
i1_0.is_book_marked,
i1_0.title,
i1_0.updated_at,
i1_0.video_id 
from
idea i1_0 
join
video v1_0 
on v1_0.id=i1_0.video_id 
join
channel c1_0 
on c1_0.id=v1_0.channel_id 
join
member m1_0 
on m1_0.id=c1_0.member_id 
where
m1_0.id=? 
and i1_0.is_book_marked=1 
order by
i1_0.created_at desc 
limit
?
기존 회원 sns 메서드에 member 파라미터가 빠져 있어서 추가하였습니다.
회원 정보 swagger 문서화도 안되어 있어서, 추가로 해두었습니다.
> [FEAT]: 북마크한 아이디어 조회

- src/main/java/channeling/be/domain/comment/domain/repository/CommentRepository.java
- src/main/java/channeling/be/domain/report/application/ReportService.java
- src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
- src/main/java/channeling/be/domain/report/domain/repository/ReportRepository.java
- src/main/java/channeling/be/domain/report/presentation/ReportController.java
- src/main/java/channeling/be/domain/report/presentation/ReportConverter.java
- src/main/java/channeling/be/domain/report/presentation/ReportResDto.java
- src/main/java/channeling/be/domain/report/presentation/ReportSwagger.java
- src/main/java/channeling/be/response/code/status/ErrorStatus.java
- src/main/java/channeling/be/response/exception/handler/ReportHandler.java
[FEAT]: 리포트의 댓글 카테고리별 조회
현재 fastapi 가 로컬에서 제대로 실행이 안돼어서,,,,,
db안에 댓글이 없어서 이렇게 나오고 있습니다.
일단 쿼리 로그로 판단하겠습니다.
1. 리포트가 존재하는 지 확인
select
r1_0.id,
r1_0.advice_comment,
r1_0.comment,
r1_0.comment_channel_avg,
r1_0.comment_topic_avg,
r1_0.concept,
r1_0.created_at,
r1_0.leave_analyze,
r1_0.like_channel_avg,
r1_0.like_count,
r1_0.like_topic_avg,
r1_0.negative_comment,
r1_0.neutral_comment,
r1_0.optimization,
r1_0.positive_comment,
r1_0.revisit,
r1_0.seo,
r1_0.summary,
r1_0.title,
r1_0.updated_at,
r1_0.video_id,
r1_0.view,
r1_0.view_channel_avg,
r1_0.view_topic_avg 
from
report r1_0 
where
r1_0.id=?
2. 리포트의 채널이 요청한 토큰의 회원 …
> [FEAT]: 리포트의 댓글 카테고리별 조회

- .github/workflows/CD.yml
- src/main/java/channeling/be/domain/auth/application/MemberOauth2UserService.java
- src/main/java/channeling/be/domain/auth/handler/Oauth2LoginSuccessHandler.java
- src/main/java/channeling/be/domain/channel/presentation/ChannelController.java
- src/main/java/channeling/be/domain/channel/presentation/ChannelSwagger.java
- src/main/java/channeling/be/domain/channel/presentation/dto/request/ChannelRequestDto.java
- src/main/java/channeling/be/domain/idea/presentation/IdeaController.java
- src/main/java/channeling/be/domain/idea/presentation/IdeaSwagger.java
- src/main/java/channeling/be/domain/member/application/MemberService.java
- src/main/java/channeling/be/domain/member/application/MemberServiceImpl.java
- src/main/java/channeling/be/domain/member/presentation/MemberController.java
- src/main/java/channeling/be/domain/member/presentation/MemberConverter.java
- src/main/java/channeling/be/domain/member/presentation/MemberResDTO.java
- src/main/java/channeling/be/domain/member/presentation/MemberSwagger.java
- src/main/java/channeling/be/domain/memberAgree/presentation/MemberAgreeApi.java
- src/main/java/channeling/be/domain/memberAgree/presentation/MemberAgreeController.java
> v1.0.0 Deploy

- .github/workflows/pr-review.yml
[BUILD] pr-review.yml 추가
- develop <- PR 시 Gemini 리뷰 받아서 코멘트로 추가
#102 
> [FEAT] pr-review.yml 추가

- src/main/java/channeling/be/domain/report/application/ReportService.java
- src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
- src/main/java/channeling/be/domain/report/domain/Report.java
- src/main/java/channeling/be/domain/report/presentation/ReportController.java
- src/main/java/channeling/be/domain/report/presentation/ReportConverter.java
- src/main/java/channeling/be/domain/report/presentation/ReportResDto.java
- src/main/java/channeling/be/domain/report/presentation/ReportSwagger.java
- src/main/java/channeling/be/domain/task/domain/repository/TaskRepository.java
- src/main/java/channeling/be/domain/video/domain/Video.java
- src/main/java/channeling/be/response/code/status/ErrorStatus.java
- src/main/resources/logback-spring.xml
리포트 조회 (report 정보 전체 반환)
리포트 개요, 분석 페이지는 동일한 로직의 report 조회이므로, 
리포트 전체 데이터를 반환하는 하나의 API 를 사용하도록 합니다.
(리포트 페이지 상단 비디오 정보 + 개요, 분석 정보)
1. API 사용될 화면
2. 동작
로그인 후 헤더의 정상 토큰과 함께 요청 시, 성공 응답입니다.
로그인 한 사용자의 리포트만 호출 가능합니다.
3. 문서
여러 페이지의 정보가 하나의 API 로 응답되므로, 프론트 연동 시 참고를 위해 미리 스웨거 문서를 작성했습니다.
#89 
> [FEAT] 리포트 조회(전체)

- src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
- task_id 생성 시간되기 전에 task_id로 리포트 조회함
- 사이에 sleep 3초 + 재시도 로직 추가
#116 
> [FEAT] 리포트 조회 메서드에 재시도 로직 추가

- src/main/java/channeling/be/domain/report/application/ReportDeleteService.java
- src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
- src/main/java/channeling/be/domain/task/domain/repository/TaskRepository.java
- 트랜잭션 중에 fastapi 에서 db 수정함 -> 이상하다고 판단해서 수정 이전 상태로 롤백 해버림
- 트랜잭션 제거 
> [FIX] 트랜잭션 롤백 오류 해결

- src/main/java/channeling/be/domain/report/application/ReportDeleteService.java
- src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
[FIX] 트랜잭션 롤백 오류 해결
- 기존 리포트 삭제 메서드 별도 클래스롤 분리해서 트랜잭션 설정
- 다른 메서드는 트랜잭션 설정 x
#121 
> v1.0.4 리포트 생성 트랜잭션 오류 해결

- .github/workflows/CD.yml
> v1.0.6 로그 디렉토리 권한 부여

- src/main/java/channeling/be/domain/report/application/ReportService.java
- src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
- src/main/java/channeling/be/domain/report/presentation/ReportController.java
- src/main/java/channeling/be/domain/report/presentation/ReportResDto.java
- src/main/java/channeling/be/domain/report/presentation/ReportSwagger.java
[FEAT]: 리포트 삭제]
우측 상단의 삭제 호버 기능 입ㄴ다.
리포트 생성 요청에서,
생성하기 전에 기존 영상이 존재한다면 삭제하는 코드 그대로입니다.
추후 수정 사항 있으면, 두가지 동시에 진행하도록 하겠습니다.
#108 
> [FEAT]: 리포트 삭제 

- build.gradle
- src/main/java/channeling/be/domain/channel/presentation/ChannelController.java
- src/main/java/channeling/be/domain/channel/presentation/ChannelSwagger.java
- src/main/java/channeling/be/domain/channel/presentation/dto/request/ChannelRequestDto.java
- src/main/java/channeling/be/domain/idea/presentation/IdeaController.java
- src/main/java/channeling/be/domain/idea/presentation/IdeaSwagger.java
- src/main/java/channeling/be/domain/member/presentation/MemberController.java
- src/main/java/channeling/be/domain/member/presentation/MemberReqDTO.java
- src/main/java/channeling/be/domain/member/presentation/MemberSwagger.java
- src/main/java/channeling/be/domain/memberAgree/presentation/MemberAgreeApi.java
- src/main/java/channeling/be/domain/memberAgree/presentation/MemberAgreeController.java
- src/main/java/channeling/be/domain/memberAgree/presentation/MemberAgreeReqDto.java
- src/main/java/channeling/be/domain/report/application/ReportService.java
- src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
- src/main/java/channeling/be/domain/report/presentation/ReportController.java
- src/main/java/channeling/be/domain/report/presentation/ReportConverter.java
- src/main/java/channeling/be/domain/report/presentation/ReportResDto.java
- src/main/java/channeling/be/domain/report/presentation/ReportSwagger.java
[CHORE]: 요청 uri restful 하게 수정 + 상태 조회 리포트로 조회하도록 수정
1. 비디오 리스트 조회 에서 member에 hidden 처리해두었습니다.
2. 멤버 동의 여부 수정 요청에서 private여서, valid로 검증이 안되어서 ,private 삭제하였습니다.
3. 멤버 동의에서 응답이 ApiResponse<?> 여서, 응답 dto를 반환하도록 수정하였습니다.
4. 리포트 서비스에서, 리포트 생성을 제외한 메서드에는 읽기 전용 트렌젝션이 추가되어야 할 거 같아서, readonly로 트랜젝션 추가해두었습니다.
5. gradle에 valid 관련 라이브러리 추가해두었습니다.
6. 카테고리별 댓글 조회 오타 수정도 반영하였습니다.
제가 최대한 오류 없이 수정하려 해보았는데, 뭔가 어딘가에서 오류가 생길 수도 있을 거 같습니다..
추후 오류 생기면 바로바로 반영하도록 하겠습니다!
4번 트랜젝션 관련해서는 이상하다 싶으면 바로 제외 하겠습니다. 이상하면 말씀해주세요!
> [CHORE]: 요청 uri restful 하게 수정 + 상태 조회 리포트로 조회하도록 수정

- src/main/java/channeling/be/domain/report/presentation/ReportController.java
- src/main/java/channeling/be/domain/report/presentation/ReportReqDto.java
- src/main/java/channeling/be/domain/report/presentation/ReportSwagger.java
- src/main/java/channeling/be/domain/video/application/VideoService.java
- src/main/java/channeling/be/domain/video/application/VideoServiceImpl.java
- src/main/java/channeling/be/domain/video/domain/repository/VideoRepository.java
- src/main/java/channeling/be/response/code/status/ErrorStatus.java
- src/main/java/channeling/be/response/exception/ExceptionAdvice.java
1. 입력 json 파싱 오류 전역 에러 처리도 추가로 진행하였습니다.
2. url 검증 후, 리포트 생성 요청은 기존 메서드를 그대로 사용합니다.
> [FEAT]: URL로 리포트 생성 요청 

- src/main/java/channeling/be/domain/channel/application/ChannelServiceImpl.java
- src/main/java/channeling/be/domain/channel/domain/Channel.java
- src/main/java/channeling/be/domain/channel/presentation/converter/ChannelConverter.java
- src/main/java/channeling/be/global/infrastructure/youtube/YoutubeUtil.java
[FEAT] 로그인시 shares수도 youtube analytics에서 가져오도록 기능 추가
로그인시 shares수도 가져오는 것을 구현
#99 
> [FEAT] 로그인시 shares수도 youtube analytics에서 가져오도록 기능 추가

- src/main/java/channeling/be/domain/auth/handler/Oauth2LoginSuccessHandler.java
- src/main/java/channeling/be/domain/member/application/MemberServiceImpl.java
- src/main/java/channeling/be/domain/member/presentation/MemberConverter.java
- src/main/java/channeling/be/domain/member/presentation/MemberResDTO.java
> v1.1.3 멤버 조회 결과에 동의 여부 추가

- .github/workflows/CD.yml
- src/main/java/channeling/be/domain/channel/presentation/ChannelConverter.java
- src/main/java/channeling/be/domain/video/domain/repository/VideoRepository.java
- src/main/java/channeling/be/domain/video/presentaion/VideoResDTO.java
> [HOTFIX] 추천 비디오 응답 채널정보 추가, CD 프론트 환경변수 누락 추가

- src/main/java/channeling/be/global/config/SecurityConfig.java
> [FEAT] CORS 허용 추가

- src/main/java/channeling/be/domain/auth/filter/JwtAuthenticationProcessingFilter.java
- src/main/java/channeling/be/domain/dummy/DummyReportServiceImpl.java
- src/main/java/channeling/be/domain/dummy/presentation/DummyController.java
- src/main/java/channeling/be/domain/dummy/presentation/DummySwagger.java
- src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
- src/main/java/channeling/be/response/code/status/ErrorStatus.java
[FEAT] 더미 레포트 정보 조회 기능 구현
메인페이지에 표기될 추천 레포트 조회시 사용
1, 2 로 각각 조회
> [FEAT] 더미 레포트 정보 조회 기능 구현

- src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
- src/main/java/channeling/be/domain/report/presentation/dto/ReportResDTO.java
> [HOTFIX] 채널의 리포트 리스트 조회 결과에 채널명 추가

- src/main/java/channeling/be/domain/report/presentation/dto/ReportResDTO.java
> v1.1.8 채널 리포트 리스트 조회에 videoId 추가

- src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
> v 1.2.1 api path /v2로 변경

- src/main/java/channeling/be/domain/report/domain/Report.java
- src/main/java/channeling/be/domain/report/presentation/ReportResDto.java
- src/main/java/channeling/be/domain/video/presentaion/VideoResDTO.java
> [FIX]: 리포트 avg long -> double

- src/main/java/channeling/be/global/config/AuditorAwareConfig.java
- src/main/java/channeling/be/global/config/JpaAuditingConfig.java
> [FIX] auditing 사용자정보 추가 버그 - CustomUserDetails -> DefaultOAuth2User 캐스팅 변경
